# -*- coding: utf-8 -*-
"""Weather Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHFpo922JcMk2trSxngx8At1JcKfBwbf
"""

import pandas as pd
import seaborn as sns
df = pd.read_csv('/content/Weather Data.csv')
df.head()
df.info()
# Number of rows and columns :
df.shape
# Shows the index range :
df.index
# Showing the columns :
df.columns
#Showing the datatype for each column :
df.dtypes
#Showing the number of unique values for each column :
df.nunique()
#Showing the total of non null values :
df.count()
df.isnull().sum()
sub_df = df[['Temp_C', 'Press_kPa', 'Rel Hum_%']]
sns.heatmap(data= sub_df.corr() , annot=True , cmap='coolwarm' )
sns.pairplot(data=sub_df.sample(1000), height=3, plot_kws={'alpha': 0.5})